#!/usr/bin/env python3
"""playtest2-digest.py - board-consumable digest of the playtest#2 analyzer.

OD-044 deep-metrics residual closer. The full analyzer `metrics.json`
(keys: summary, p3_promotions, p4_psicologico, p6_fairness,
od024_interoception, od026_atlas, performance) lives ONLY inside Game's
auth-gated workflow ARTIFACT, so codemasterdd's cross-repo raw-fetch
(no auth) cannot read it. This script distills the board-relevant subset
into a small, STABLE, git-committed public file
(`tools/sim/playtest2-latest.json`) that codemasterdd CAN raw-fetch -
mirroring the existing `tools/sim/pillar-baseline.json` precedent and
committed in the SAME auto-PR (same idempotency / bootstrap guard).

Contract (honest + defensive by design):
  - metrics.json missing / unreadable / not-JSON  -> exit 0, write nothing
    (the caller's git-diff guard then yields NO PR - graceful no-op).
  - metrics.json present + valid                  -> write digest, exit 0.
  - Any individual field absent in metrics.json   -> emitted as null
    (never fabricated; the board renders "n/a" honestly).

Per-pillar verdict is derived from the SAME thresholds the analyzer's
markdown report uses (`_verdict_emoji`: >= min_sample green, >= partial
yellow, else red; P4 = all 4 layers complete). No new policy is invented.

Usage:
  python tools/sim/playtest2-digest.py \
    --metrics <analyzer metrics.json> \
    --out tools/sim/playtest2-latest.json \
    [--run-id <gh run id>] [--min-sample 30]
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import sys
from pathlib import Path

# Mirror tools/py/playtest_2_analyzer.py partial-sample floor. Kept as a
# local constant so a missing/old metrics.json never crashes the digest.
MIN_SAMPLE_PARTIAL = 10


def _verdict(metric_count: int, min_sample: int) -> str:
    """Same coarse gate as the analyzer's `_verdict_emoji`, as plain text."""
    if metric_count >= min_sample:
        return "green"
    if metric_count >= MIN_SAMPLE_PARTIAL:
        return "partial"
    return "red"


def _num(d: dict, key: str):
    """Fetch a numeric field, returning None (never fabricated) if absent."""
    v = d.get(key)
    return v if isinstance(v, (int, float)) else None


def build_digest(metrics: dict, *, run_id, min_sample: int) -> dict:
    summary = metrics.get("summary") or {}
    p3 = metrics.get("p3_promotions") or {}
    p4 = metrics.get("p4_psicologico") or {}
    p6 = metrics.get("p6_fairness") or {}
    od024 = metrics.get("od024_interoception") or {}
    od026 = metrics.get("od026_atlas") or {}
    perf = metrics.get("performance") or {}

    sample_size = summary.get("total_sessions")
    sample_n = sample_size if isinstance(sample_size, int) else 0

    p4_layers = p4.get("layer_completeness") or {}
    p4_complete = bool(p4_layers) and all(p4_layers.values())

    biome_focus = od026.get("biome_focus_events") or {}
    p3_promos = p3.get("total_promotions")
    p3_promos_n = p3_promos if isinstance(p3_promos, int) else 0

    return {
        "_schema": "playtest2-latest/1",
        "_note": (
            "Board-consumable subset of the playtest#2 analyzer metrics. "
            "Generated by tools/sim/playtest2-digest.py, committed in the "
            "ai-sim-nightly baseline-update PR. Null = analyzer did not "
            "produce that field (honest, never fabricated)."
        ),
        "generated_at": _dt.datetime.now(_dt.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        ),
        "run_id": str(run_id) if run_id else None,
        "sample_size": sample_size if isinstance(sample_size, int) else None,
        "min_sample": min_sample,
        # Overall verdict: ABORT perf gate dominates, else sample gate
        # (mirrors the analyzer report's coarse intent without re-running
        # the JS check-pillar-baselines computeVerdict).
        "verdict": (
            "regression"
            if perf.get("command_latency_verdict") == "ABORT"
            else _verdict(sample_n, min_sample)
        ),
        "pillars": {
            "p3": {
                "verdict": _verdict(p3_promos_n, min_sample),
                "key_metric": _num(p3, "total_promotions"),
            },
            "p4": {
                "verdict": "green" if p4_complete else "partial",
                "4layer_completeness": p4_layers or None,
            },
            "p6": {
                "verdict": _verdict(sample_n, min_sample),
                "rewind_pct": _num(p6, "rewind_sessions_pct"),
            },
            "od024": {
                "firing_pct": _num(od024, "firing_rate_pct"),
            },
            "od026": {
                "skiv_pulse": _num(od026, "skiv_pulse_events"),
                "biome_focus": (
                    len(biome_focus) if isinstance(biome_focus, dict) else None
                ),
            },
            "performance": {
                "p95_ms": _num(perf, "command_latency_p95_ms"),
                "verdict": perf.get("command_latency_verdict") or None,
            },
        },
    }


def main() -> int:
    ap = argparse.ArgumentParser(description="playtest#2 board-consumable digest")
    ap.add_argument("--metrics", required=True, help="analyzer metrics.json path")
    ap.add_argument("--out", required=True, help="digest output path")
    ap.add_argument("--run-id", default=None, help="GitHub Actions run id (optional)")
    ap.add_argument("--min-sample", type=int, default=30)
    args = ap.parse_args()

    src = Path(args.metrics)
    if not src.is_file():
        # Honest no-op: analyzer produced nothing this run (e.g. no batch
        # runs dir, or the analyzer step skipped). Write nothing so the
        # caller's git-diff guard opens NO PR.
        print(
            f"[playtest2-digest] metrics absent ({src}) - graceful no-op, "
            "no digest written",
            file=sys.stderr,
        )
        return 0
    try:
        metrics = json.loads(src.read_text(encoding="utf-8"))
        if not isinstance(metrics, dict):
            raise ValueError("metrics.json top-level is not an object")
    except (json.JSONDecodeError, ValueError, OSError) as err:
        print(
            f"[playtest2-digest] metrics unreadable/invalid ({err}) - "
            "graceful no-op, no digest written",
            file=sys.stderr,
        )
        return 0

    digest = build_digest(metrics, run_id=args.run_id, min_sample=args.min_sample)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        json.dumps(digest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"[playtest2-digest] digest written: {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
