schema_version: '1.0'
types:
  cursoriale_quadrupede:
    default_slots:
      locomotion: 1
      offense: 1
      defense: 1
      senses: 1
    bias:
    - Skirmisher
    - Vanguard
  volatore_planatore:
    default_slots:
      locomotion: 1
      offense: 1
      senses: 1
    bias:
    - Skirmisher
    - Invoker
  scavenger_corazzato:
    default_slots:
      defense: 2
      offense: 1
      senses: 1
    bias:
    - Warden
    - Vanguard
  ingegnere_radicante:
    default_slots:
      defense: 1
      senses: 1
    bias:
    - Artificer
    - Warden
  anfibio_filtratore:
    default_slots:
      locomotion: 1
      senses: 1
    bias:
    - Invoker
    - Artificer
slot_caps:
  defense: 3
  offense: 2
  locomotion: 2
  senses: 2
  metabolism: 1
