version: 0.1.0
requirements:
  shelter: "Riparo stabile (tenda/covo)"
  resources: "2 unità di nutrimento equivalenti"
  security: "Area senza minacce attive entro 50 m"
checks:
  - id: basic_nest_check
    rule: "Se tutti i requisiti sono soddisfatti, nest_requirements_ok = true per la scena/missione."
notes: >
  Alcuni partner richiedono standard superiori (comfort, temperatura, ecc.).
