version: 0.1.0
preferences:
  dune_stalker:
    likes: ["flanking","preda isolata","eco vantaggiosa"]
    dislikes: ["fuoco continuo","rumore al nido"]
  sand_burrower:
    likes: ["ambush","terreno soffice","uscite improvvise"]
    dislikes: ["vetrificazione", "trappole a rete"]
  echo_wing:
    likes: ["quota","linee di tiro lunghe","rimbalzi sonori"]
    dislikes: ["strettoie", "reti"]
  rust_scavenger:
    likes: ["rottami","coperture","magnetismo debole"]
    dislikes: ["campi magnetici forti","acidi forti"]
