#!/usr/bin/env python3
"""Seed jobs.yaml trait_abilities section from trait_mechanics.yaml.

ADR-2026-05-29-trait-schema-canonization TKT-CL-06 + TKT-CL-07. Closes
30 trait-mech gap (c) per Game docs/research/2026-05-10-trait-mech-no-handler-audit.md
(0/39 ability_id registered in jobs.yaml = silent no-op on dispatch).

Output: appends `trait_abilities:` section at end of data/core/jobs.yaml.

Idempotent: re-run skips if section already present (prints WARN).

Usage:
    python tools/scripts/seed_trait_abilities_from_mechanics.py [--dry-run]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
MECH = REPO / "packs/evo_tactics_pack/data/balance/trait_mechanics.yaml"
JOBS = REPO / "data/core/jobs.yaml"

SKIP_TOP_KEYS = {"_defaults", "schema_version", "generated_from", "notes"}


def _load_yaml(path: Path):
    import yaml
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _render_ability(trait_id: str, ae: dict):
    ability_id = ae.get("ability_id")
    if not ability_id:
        return None
    effect_type = ae.get("effect_type")
    base = {
        "ability_id": ability_id,
        "name_it": ae.get("name_it", trait_id.replace("_", " ").title()),
        "cost_ap": int(ae.get("cost_ap", 2)),
        "cost_pi": 0,
        "effect_type": effect_type,
        "target": ae.get("target", "self"),
        "rank": 1,
        "source": "trait",
        "source_trait_id": trait_id,
    }
    if effect_type == "buff":
        base["buff_stat"] = ae.get("buff_stat", "attack_mod")
        base["buff_amount"] = int(ae.get("buff_amount", 1))
        base["buff_duration"] = int(ae.get("buff_duration", 1))
    elif effect_type == "heal":
        dice = ae.get("heal_dice", {"count": 1, "sides": 4, "modifier": 1})
        base["heal_dice"] = {
            "count": int(dice.get("count", 1)),
            "sides": int(dice.get("sides", 4)),
            "modifier": int(dice.get("modifier", 1)),
        }
    elif effect_type == "damage":
        dice = ae.get("damage_dice", {"count": 1, "sides": 6, "modifier": 1})
        base["damage_dice"] = {
            "count": int(dice.get("count", 1)),
            "sides": int(dice.get("sides", 6)),
            "modifier": int(dice.get("modifier", 1)),
        }
        base["channel"] = ae.get("channel", "fisico")
        if base["target"] == "self":
            base["target"] = "enemy"
    elif effect_type == "apply_status":
        base["status_id"] = ae.get("status_id", ae.get("status", "disorient"))
        base["status_duration"] = int(ae.get("status_duration", ae.get("turns", 1)))
        if base["target"] == "self":
            base["target"] = "enemy"
    else:
        print(f"WARN unknown effect_type {effect_type!r} for {ability_id}", file=sys.stderr)
    return base


def collect_abilities(mech: dict):
    out = {}
    # trait_mechanics.yaml shape: {schema_version, generated_from, notes, _defaults, traits: {...}}
    traits = mech.get("traits") or {}
    for trait_id, trait_data in traits.items():
        if trait_id in SKIP_TOP_KEYS:
            continue
        if not isinstance(trait_data, dict):
            continue
        ae_list = trait_data.get("active_effects") or []
        for ae in ae_list:
            if not isinstance(ae, dict):
                continue
            entry = _render_ability(trait_id, ae)
            if entry:
                out[entry["ability_id"]] = entry
    return out


def render_yaml_section(abilities):
    import yaml
    section = {"trait_abilities": dict(sorted(abilities.items()))}
    return yaml.safe_dump(section, sort_keys=False, allow_unicode=True, width=120)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    mech = _load_yaml(MECH)
    abilities = collect_abilities(mech)

    print(f"# Generated {len(abilities)} trait_abilities from {MECH.name}", file=sys.stderr)
    by_type = {}
    for a in abilities.values():
        t = a.get("effect_type", "unknown")
        by_type[t] = by_type.get(t, 0) + 1
    print(f"# By effect_type: {by_type}", file=sys.stderr)

    rendered = render_yaml_section(abilities)

    if args.dry_run:
        print(rendered)
        return 0

    current = JOBS.read_text(encoding="utf-8")
    marker = "\ntrait_abilities:"
    if marker in current:
        print(f"WARN trait_abilities section already present in {JOBS}", file=sys.stderr)
        return 1

    appended = (
        current.rstrip("\n")
        + "\n\n"
        + "# ADR-2026-05-29 TKT-CL-06/CL-07: trait_abilities section.\n"
        + "# Generated by tools/scripts/seed_trait_abilities_from_mechanics.py\n"
        + "# from packs/evo_tactics_pack/data/balance/trait_mechanics.yaml.\n"
        + "# Closes 0/39 ability_id gap per audit 2026-05-10-trait-mech-no-handler-audit.md.\n"
        + "# Consumer: apps/backend/services/abilityExecutor.js (source: trait marker).\n"
        + "\n"
        + rendered
    )
    JOBS.write_text(appended, encoding="utf-8")
    print(f"# Wrote section to {JOBS}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
