// Shared DO-NOT-EDIT marker emitted into the generated evo-pack catalog files
// (catalog_data.json, per-file species/*.json, and the species index files).
//
// The value is STATIC (no timestamps/random) so regeneration stays idempotent:
// `npm run sync:evo-pack` only rewrites a file when its non-timestamp content
// changes, so a constant marker never churns. The marker is deliberately NOT in
// TIMESTAMP_KEYS, so it is part of the compared contract -- the CI
// regenerate-and-diff gate (dataset-checks) reverts any hand-edit that drops or
// alters it.
//
// Phase A / L1 generation-enforcement, see
// docs/planning/2026-06-18-taxonomy-reconciliation-plan.md.

const GENERATED_MARKER =
  "DO NOT EDIT -- generated by 'npm run sync:evo-pack' (scripts/update_evo_pack_catalog.js). Edit the source YAML/JSON instead.";

module.exports = { GENERATED_MARKER };
