"""Tests for tools/docs_governance_migrator.py helper functions and CLI subcommands."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from unittest.mock import patch

import pytest

# Ensure the tools directory is importable
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tools"))
import docs_governance_migrator as migrator


# ---------------------------------------------------------------------------
# parse_frontmatter
# ---------------------------------------------------------------------------

class TestParseFrontmatter:
    def test_valid_frontmatter(self, tmp_path: Path):
        md = tmp_path / "doc.md"
        md.write_text("---\ntitle: Hello\ndoc_status: active\n---\n# Body\n", encoding="utf-8")
        fm = migrator.parse_frontmatter(md)
        assert fm is not None
        assert fm["title"] == "Hello"
        assert fm["doc_status"] == "active"

    def test_no_frontmatter(self, tmp_path: Path):
        md = tmp_path / "doc.md"
        md.write_text("# Just a heading\nSome text.\n", encoding="utf-8")
        assert migrator.parse_frontmatter(md) is None

    def test_boolean_and_int_parsing(self, tmp_path: Path):
        md = tmp_path / "doc.md"
        md.write_text("---\nsource_of_truth: true\nprimary: false\nreview_cycle_days: 14\n---\n", encoding="utf-8")
        fm = migrator.parse_frontmatter(md)
        assert fm["source_of_truth"] is True
        assert fm["primary"] is False
        assert fm["review_cycle_days"] == 14

    def test_utf8_bom(self, tmp_path: Path):
        md = tmp_path / "doc.md"
        md.write_bytes(b"\xef\xbb\xbf---\ntitle: BOM\n---\n# Content\n")
        fm = migrator.parse_frontmatter(md)
        assert fm is not None
        assert fm["title"] == "BOM"

    def test_unclosed_frontmatter_returns_none(self, tmp_path: Path):
        md = tmp_path / "doc.md"
        md.write_text("---\ntitle: Broken\nNo closing delimiter\n", encoding="utf-8")
        assert migrator.parse_frontmatter(md) is None

    def test_nonexistent_file_returns_none(self, tmp_path: Path):
        assert migrator.parse_frontmatter(tmp_path / "missing.md") is None


# ---------------------------------------------------------------------------
# extract_title
# ---------------------------------------------------------------------------

class TestExtractTitle:
    def test_heading_title(self, tmp_path: Path):
        md = tmp_path / "doc.md"
        md.write_text("---\ntitle: FM Title\n---\n# Actual Title\nBody.\n", encoding="utf-8")
        assert migrator.extract_title(md) == "Actual Title"

    def test_no_heading_uses_filename(self, tmp_path: Path):
        md = tmp_path / "my-cool-doc.md"
        md.write_text("Just some text, no heading.\n", encoding="utf-8")
        assert migrator.extract_title(md) == "My Cool Doc"

    def test_skips_h2(self, tmp_path: Path):
        md = tmp_path / "doc.md"
        md.write_text("## Not H1\nSome text.\n", encoding="utf-8")
        assert migrator.extract_title(md) == "Doc"


# ---------------------------------------------------------------------------
# infer_workstream
# ---------------------------------------------------------------------------

class TestInferWorkstream:
    @pytest.mark.parametrize("path,expected", [
        ("docs/hubs/combat.md", "cross-cutting"),
        ("docs/core/01-VISIONE.md", "cross-cutting"),
        ("docs/guide/INTEGRAZIONE.md", "cross-cutting"),
        ("docs/pipelines/golden.md", "flow"),
        ("docs/architecture/tri-sorgente.md", "flow"),
        ("docs/frontend/app.md", "atlas"),
        ("docs/traits/index.md", "dataset-pack"),
        ("docs/ci/workflow.md", "ops-qa"),
        ("docs/generated/pr-summaries/log.md", "ops-qa"),
        ("docs/incoming/draft.md", "incoming"),
        ("docs/random/unknown.md", "cross-cutting"),
    ])
    def test_mapping(self, path: str, expected: str):
        assert migrator.infer_workstream(path) == expected

    def test_backslash_normalization(self):
        assert migrator.infer_workstream("docs\\traits\\index.md") == "dataset-pack"


# ---------------------------------------------------------------------------
# is_autogenerated
# ---------------------------------------------------------------------------

class TestIsAutogenerated:
    def test_autogen_path(self):
        assert migrator.is_autogenerated("docs/generated/pr-summaries/log.md") is True
        assert migrator.is_autogenerated("docs/evo-tactics-pack/reports/r.md") is True

    def test_non_autogen_path(self):
        assert migrator.is_autogenerated("docs/hubs/combat.md") is False

    def test_content_marker(self):
        assert migrator.is_autogenerated("docs/any.md", "_Generato automaticamente da script") is True
        assert migrator.is_autogenerated("docs/any.md", "<!-- generated --> content") is True

    def test_no_marker(self):
        assert migrator.is_autogenerated("docs/any.md", "Normal content without markers") is False


# ---------------------------------------------------------------------------
# classify_tier
# ---------------------------------------------------------------------------

class TestClassifyTier:
    def test_critical_root(self):
        assert migrator.classify_tier("README.md") == "critical"
        assert migrator.classify_tier("CLAUDE.md") == "critical"

    def test_critical_path(self):
        assert migrator.classify_tier("docs/adr/some-decision.md") == "critical"
        assert migrator.classify_tier("docs/hubs/combat.md") == "critical"

    def test_standard_path(self):
        assert migrator.classify_tier("docs/planning/roadmap.md") == "standard"
        assert migrator.classify_tier("docs/checklist/deploy.md") == "standard"

    def test_numbered_standard(self):
        assert migrator.classify_tier("docs/10-SISTEMA_TATTICO.md") == "standard"

    def test_low_default(self):
        assert migrator.classify_tier("docs/random/notes.md") == "low"

    def test_nested_root_file_not_critical(self):
        # README.md inside a subdirectory is NOT critical root file
        assert migrator.classify_tier("docs/sub/README.md") != "critical"


# ---------------------------------------------------------------------------
# build_frontmatter_block
# ---------------------------------------------------------------------------

class TestBuildFrontmatterBlock:
    def test_basic_output(self):
        with patch.object(migrator, "today_str", return_value="2026-04-14"):
            block = migrator.build_frontmatter_block("Test Doc", "flow", "docs/pipelines/test.md")
        assert block.startswith("---\n")
        assert block.endswith("---\n")
        assert "title: Test Doc" in block
        assert "workstream: flow" in block
        assert "doc_owner: flow-team" in block
        assert "review_cycle_days: 14" in block

    def test_archive_30_day_cycle(self):
        with patch.object(migrator, "today_str", return_value="2026-04-14"):
            block = migrator.build_frontmatter_block("Old Doc", "incoming", "docs/archive/old.md")
        assert "review_cycle_days: 30" in block

    def test_unknown_workstream_default_owner(self):
        with patch.object(migrator, "today_str", return_value="2026-04-14"):
            block = migrator.build_frontmatter_block("Doc", "unknown-ws", "docs/x.md")
        assert "doc_owner: platform-docs" in block


# ---------------------------------------------------------------------------
# collect_md_files
# ---------------------------------------------------------------------------

class TestCollectMdFiles:
    def test_collects_from_docs_reports_root(self, tmp_path: Path):
        (tmp_path / "docs").mkdir()
        (tmp_path / "docs" / "a.md").write_text("# A", encoding="utf-8")
        (tmp_path / "docs" / "sub").mkdir()
        (tmp_path / "docs" / "sub" / "b.md").write_text("# B", encoding="utf-8")
        (tmp_path / "reports").mkdir()
        (tmp_path / "reports" / "r.md").write_text("# R", encoding="utf-8")
        (tmp_path / "ROOT.md").write_text("# Root", encoding="utf-8")

        files = migrator.collect_md_files(tmp_path)
        rel_paths = {f.relative_to(tmp_path).as_posix() for f in files}
        assert "docs/a.md" in rel_paths
        assert "docs/sub/b.md" in rel_paths
        assert "reports/r.md" in rel_paths
        assert "ROOT.md" in rel_paths


# ---------------------------------------------------------------------------
# registry helpers
# ---------------------------------------------------------------------------

class TestRegistryHelpers:
    def test_load_save_round_trip(self, tmp_path: Path):
        reg = {"entries": [{"path": "docs/b.md"}, {"path": "docs/a.md"}]}
        path = tmp_path / "registry.json"
        path.write_text(json.dumps(reg), encoding="utf-8")

        loaded = migrator.load_registry(path)
        migrator.save_registry(path, loaded)
        reloaded = json.loads(path.read_text(encoding="utf-8"))
        # Entries should be sorted by path after save
        assert reloaded["entries"][0]["path"] == "docs/a.md"
        assert reloaded["entries"][1]["path"] == "docs/b.md"

    def test_registry_paths(self):
        reg = {"entries": [{"path": "a.md"}, {"path": "b.md"}, {"no_path": True}]}
        assert migrator.registry_paths(reg) == {"a.md", "b.md"}


# ---------------------------------------------------------------------------
# cmd_scan (integration)
# ---------------------------------------------------------------------------

class TestCmdScan:
    def test_scan_writes_json_report(self, tmp_path: Path):
        docs = tmp_path / "docs"
        docs.mkdir()
        (docs / "test.md").write_text("---\ntitle: T\nworkstream: flow\n---\n# T\n", encoding="utf-8")

        report_path = tmp_path / "out" / "report.json"
        args = argparse.Namespace(command="scan", report=str(report_path))

        ret = migrator.cmd_scan(args, tmp_path)
        assert ret == 0
        assert report_path.exists()

        data = json.loads(report_path.read_text(encoding="utf-8"))
        assert data["summary"]["total"] >= 1
        assert any(f["path"] == "docs/test.md" for f in data["files"])


# ---------------------------------------------------------------------------
# cmd_generate_frontmatter (integration)
# ---------------------------------------------------------------------------

class TestCmdGenerateFrontmatter:
    def test_dry_run_does_not_modify(self, tmp_path: Path):
        docs = tmp_path / "docs"
        docs.mkdir()
        md = docs / "bare.md"
        md.write_text("# No Frontmatter\nBody.\n", encoding="utf-8")
        original = md.read_text(encoding="utf-8")

        args = argparse.Namespace(command="generate-frontmatter", dry_run=True, path=None, workstream=None)
        ret = migrator.cmd_generate_frontmatter(args, tmp_path)
        assert ret == 0
        assert md.read_text(encoding="utf-8") == original

    def test_adds_frontmatter(self, tmp_path: Path):
        docs = tmp_path / "docs" / "traits"
        docs.mkdir(parents=True)
        md = docs / "bare.md"
        md.write_text("# Trait Doc\nBody.\n", encoding="utf-8")

        args = argparse.Namespace(command="generate-frontmatter", dry_run=False, path=None, workstream=None)
        with patch.object(migrator, "today_str", return_value="2026-04-14"):
            ret = migrator.cmd_generate_frontmatter(args, tmp_path)
        assert ret == 0
        content = md.read_text(encoding="utf-8")
        assert content.startswith("---\n")
        assert "workstream: dataset-pack" in content
        assert "# Trait Doc" in content

    def test_skips_existing_frontmatter(self, tmp_path: Path):
        docs = tmp_path / "docs"
        docs.mkdir()
        md = docs / "existing.md"
        md.write_text("---\ntitle: Existing\n---\n# Existing\n", encoding="utf-8")
        original = md.read_text(encoding="utf-8")

        args = argparse.Namespace(command="generate-frontmatter", dry_run=False, path=None, workstream=None)
        migrator.cmd_generate_frontmatter(args, tmp_path)
        assert md.read_text(encoding="utf-8") == original
