#!/usr/bin/env python3
"""O3 pattern (OpenRA auto-docs): genera documentazione trait da YAML.

Legge trait_mechanics.yaml e produce Markdown reference table.
Output: docs/generated/trait-reference.md

Uso:
    python tools/py/gen_trait_docs.py
    python tools/py/gen_trait_docs.py --out docs/generated/trait-reference.md
"""

import argparse
import sys
from pathlib import Path

import yaml


DEFAULT_INPUT = "packs/evo_tactics_pack/data/balance/trait_mechanics.yaml"
DEFAULT_OUTPUT = "docs/generated/trait-reference.md"


def load_traits(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return data.get("traits", {})


def classify_trait(t: dict) -> str:
    """Classifica trait in base ai mod (euristica dal README balance)."""
    atk = t.get("attack_mod", 0)
    dfn = t.get("defense_mod", 0)
    step = t.get("damage_step", 0)
    if atk > 0 and dfn == 0:
        return "offensive"
    if dfn > 0 and atk == 0:
        return "defensive"
    if atk > 0 and dfn > 0:
        return "hybrid"
    if t.get("cost_ap", 1) < 1:
        return "mobility"
    return "utility"


def format_resistances(resistances: list) -> str:
    if not resistances:
        return "—"
    parts = []
    for r in resistances:
        ch = r.get("channel", "?")
        pct = r.get("modifier_pct", 0)
        sign = "+" if pct > 0 else ""
        parts.append(f"{ch} {sign}{pct}%")
    return ", ".join(parts)


def format_abilities(effects: list) -> str:
    if not effects:
        return "—"
    parts = []
    for e in effects:
        name = e.get("name_it", e.get("ability_id", "?"))
        cost = e.get("cost_ap", "?")
        etype = e.get("effect_type", "?")
        parts.append(f"{name} (AP:{cost}, {etype})")
    return "; ".join(parts)


def generate_markdown(traits: dict, schema_version: str = "?") -> str:
    lines = [
        "<!-- AUTO-GENERATED by tools/py/gen_trait_docs.py — do not edit manually -->",
        "",
        f"# Trait Reference (v{schema_version})",
        "",
        f"Generato da `trait_mechanics.yaml`. {len(traits)} trait totali.",
        "",
        "| Trait | Classe | ATK | DEF | Step | AP | Resistenze | Abilita |",
        "| --- | --- | ---: | ---: | ---: | ---: | --- | --- |",
    ]

    for trait_id, t in sorted(traits.items()):
        cls = classify_trait(t)
        atk = t.get("attack_mod", 0)
        dfn = t.get("defense_mod", 0)
        step = t.get("damage_step", 0)
        ap = t.get("cost_ap", 1)
        res = format_resistances(t.get("resistances") or [])
        abilities = format_abilities(t.get("active_effects") or [])
        lines.append(
            f"| `{trait_id}` | {cls} | {atk} | {dfn} | {step} | {ap} | {res} | {abilities} |"
        )

    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate trait reference docs from YAML")
    parser.add_argument("--input", default=DEFAULT_INPUT, help="Path to trait_mechanics.yaml")
    parser.add_argument("--out", default=DEFAULT_OUTPUT, help="Output markdown path")
    args = parser.parse_args()

    data_path = Path(args.input)
    if not data_path.exists():
        print(f"ERROR: {data_path} not found", file=sys.stderr)
        sys.exit(1)

    with open(data_path, "r", encoding="utf-8") as f:
        full_data = yaml.safe_load(f)

    traits = full_data.get("traits", {})
    version = full_data.get("schema_version", "?")

    md = generate_markdown(traits, version)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding="utf-8")
    print(f"[gen_trait_docs] {len(traits)} traits -> {out_path}")


if __name__ == "__main__":
    main()
