#!/usr/bin/env python3
"""Generate A.L.I.E.N.A. codex lore DRAFTs for the 13 ratified retired creatures.

Salvage program, verdict 4 (master-dd 2026-06-23): the 13 retired-creature
identities were ratified (docs/planning/2026-06-22-retired-creatures-salvage-proposal.md)
and their gameplay specs shipped (#3032) under
packs/evo_tactics_pack/data/species/<biome>/<id>.yaml. This driver narrativizes
each spec into a codex DRAFT via the repo's seeded Tracery grammar
(codex_draft_scaffold -> codex_aliena_lore_gen).

WHY A DRIVER (the established salvage idiom -- cf. gen_retired_creature_specs.py,
author_appendix_a_variant_traits.py): codex_draft_scaffold's stub path reads
`trait_refs`, but a pack species stores its kit in `genetic_traits` /
`derived_from_environment.suggested_traits`. So a bare stub scaffold loses the
SALVAGED KIT (the creature's whole identity) from both the prose and the codex
data (key_facts / cross_ref). This driver NORMALIZES the kit into `trait_refs`
first, then scaffolds in RICH mode -- so each draft's L_linee_evolutive weaves
the recovered kit and the codex data carries `trait:*` cross_refs. The visual /
lifecycle / mutation rich slots fall back gracefully (no lifecycle file yet, no
authored visual_description -> morphotype fallback, no i18n leak). No shared-tool
edit; reproducible; scoped to exactly these 13.

HITL GATE (non-negotiable): every output is stamped
`lore_review_status: generated_pending_review`; tools/js/promote_codex_draft.js
REFUSES to promote it. master-dd reviews/edits the prose and flips the status to
`human_reviewed` before promotion. Machine prose NEVER reaches a player unreviewed.

Usage:
    PYTHONPATH=tools/py python tools/py/gen_retired_creature_lore_drafts.py
    PYTHONPATH=tools/py python tools/py/gen_retired_creature_lore_drafts.py --print
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Dict, List, Optional

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import codex_draft_scaffold as scaf  # noqa: E402
import codex_aliena_lore_gen as gen  # noqa: E402

# The 13 ratified retired-creature ids (proposal doc, RATIFIED 2026-06-23).
# #13 resonant_claw_hunter is deferred (museum, THIN single-trait) -> not here.
RETIRED_IDS = [
    "heliopteryx_radians",
    "pyroflagellum_meteoriticum",
    "sonovespera_lamentans",
    "tellurmordax_phasicus",
    "auroserpens_photonicus",
    "lithoconstructus_inhibens",
    "amorphovenator_magneticus",
    "rotabrachium_ferox",
    "aerostatocyon_altivolans",
    "filtrophagus_custos",
    "cryptopennatus_psionicus",
    "illusiopardus_psionicus",
    "radiciforma_ancorans",
]

SPECIES_ROOT = Path("packs/evo_tactics_pack/data/species")
DEFAULT_OUT_DIR = "data/codex/_drafts"
PROMOTED_DIR = Path("data/codex")

_HEADER = (
    "# Generated by tools/py/gen_retired_creature_lore_drafts.py -- PENDING master-dd review.\n"
    "# Salvage verdict 4: lore DRAFT for a ratified retired creature. lore_vars +\n"
    "# the 6 content: blocks are GENERATED from the species spec (kit woven via the\n"
    "# seeded grammar). Edit the prose, set lore_review_status: human_reviewed (or\n"
    "# remove it), then `node tools/js/promote_codex_draft.js {sid}`.\n"
)


def normalize_trait_refs(species: Dict) -> List[str]:
    """Union the species' kit into a flat, order-preserving, deduped trait_refs.

    Source = genetic_traits.core/optional/synergy + derived suggested_traits.
    These are the glossary-covered signature traits the spec retained (#3032
    filtered out glossary-less ones), so they are canon-safe to surface.
    """
    gt = species.get("genetic_traits") or {}
    derived = species.get("derived_from_environment") or {}
    ordered: List[str] = []
    for bucket in (
        gt.get("core") or [],
        gt.get("optional") or [],
        gt.get("synergy") or [],
        derived.get("suggested_traits") or [],
    ):
        for trait in bucket:
            if trait and trait not in ordered:
                ordered.append(str(trait))
    return ordered


def build_draft(spec_path: Path, biomes_doc: Dict, grammar: Dict) -> Dict:
    """Load a species spec, normalize its kit into trait_refs, scaffold RICH."""
    species = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
    trait_refs = normalize_trait_refs(species)
    if trait_refs:
        species["trait_refs"] = trait_refs
    return scaf.scaffold_draft(
        species, biomes_doc, grammar, lifecycle_doc={}, rich=bool(trait_refs)
    )


def _index_specs() -> Dict[str, Path]:
    """Map each RETIRED id -> its spec file path (filenames are hyphenated)."""
    wanted = set(RETIRED_IDS)
    found: Dict[str, Path] = {}
    for path in sorted(SPECIES_ROOT.rglob("*.yaml")):
        try:
            doc = yaml.safe_load(path.read_text(encoding="utf-8"))
        except (yaml.YAMLError, OSError):
            continue
        sid = (doc or {}).get("id")
        if sid in wanted and sid not in found:
            found[sid] = path
    return found


def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(description="Generate retired-creature codex lore drafts")
    p.add_argument("--biomes", default="data/core/biomes.yaml")
    p.add_argument("--grammar", default=gen.DEFAULT_GRAMMAR_PATH)
    p.add_argument("--out-dir", default=DEFAULT_OUT_DIR)
    p.add_argument("--print", action="store_true", help="print drafts to stdout, do not write")
    p.add_argument(
        "--force",
        action="store_true",
        help="overwrite existing draft files (default: skip existing to preserve manual edits)",
    )
    args = p.parse_args(argv)

    biomes_doc = yaml.safe_load(Path(args.biomes).read_text(encoding="utf-8"))
    grammar = gen.load_grammar(args.grammar)
    specs = _index_specs()

    missing = [sid for sid in RETIRED_IDS if sid not in specs]
    if missing:
        print(f"ERROR: spec(s) not found on disk: {', '.join(missing)}", file=sys.stderr)
        return 2

    out_dir = Path(args.out_dir)
    # FIX 4: guard against bypassing the HITL promote gate
    if out_dir.resolve() == PROMOTED_DIR.resolve():
        print(
            f"ERROR: --out-dir resolves to the promoted dir ({PROMOTED_DIR}). "
            "Writing directly to data/codex/ bypasses the HITL review gate. "
            "Use the default _drafts/ dir and promote via tools/js/promote_codex_draft.js.",
            file=sys.stderr,
        )
        return 1
    out_dir.mkdir(parents=True, exist_ok=True)
    wrote = 0
    for sid in RETIRED_IDS:
        if (PROMOTED_DIR / f"{sid}.yaml").exists():
            print(f"SKIP {sid}: already promoted (data/codex/{sid}.yaml exists)", file=sys.stderr)
            continue
        draft = build_draft(specs[sid], biomes_doc, grammar)
        if args.print:
            print(f"# ===== {sid} =====")
            print(yaml.safe_dump(draft, allow_unicode=True, sort_keys=False, width=88))
            continue
        out = out_dir / f"{sid}.yaml"
        # FIX 5: don't clobber manual master-dd edits unless --force is set
        if out.exists() and not args.force:
            print(f"SKIP {sid}: draft already exists at {out} (use --force to overwrite)", file=sys.stderr)
            continue
        with open(out, "w", encoding="utf-8") as fh:
            fh.write(_HEADER.format(sid=sid))
            yaml.safe_dump(draft, fh, allow_unicode=True, sort_keys=False, width=88)
        print(f"WROTE {out} (pending review)")
        wrote += 1
    if not args.print:
        print(f"\n{wrote} draft(s) written to {out_dir} (all generated_pending_review).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
