#!/usr/bin/env python3
"""L1 pattern (langium alternative): genera types multi-target da trait_mechanics.yaml.

Genera da un'unica source of truth (YAML):
  - TypeScript interfaces (packages/contracts/generated/traitTypes.ts)
  - JSON Schema (packages/contracts/generated/traitMechanics.generated.schema.json)

Uso:
    python tools/py/gen_trait_types.py
    python tools/py/gen_trait_types.py --input path/to/trait_mechanics.yaml
"""

import argparse
import json
import sys
from pathlib import Path

import yaml


DEFAULT_INPUT = "packs/evo_tactics_pack/data/balance/trait_mechanics.yaml"
TS_OUTPUT = "packages/contracts/generated/traitTypes.ts"
SCHEMA_OUTPUT = "packages/contracts/generated/traitMechanics.generated.schema.json"


def load_yaml(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def extract_trait_shape(traits: dict) -> dict:
    """Estrae lo shape comune dai trait per generare types."""
    fields = {}
    for trait_id, t in traits.items():
        for key, val in t.items():
            if key not in fields:
                fields[key] = type(val).__name__
    return fields


def gen_typescript(traits: dict, version: str) -> str:
    """Genera TypeScript interfaces."""
    trait_ids = sorted(traits.keys())
    lines = [
        "// AUTO-GENERATED by tools/py/gen_trait_types.py -- do not edit manually",
        f"// Source: trait_mechanics.yaml v{version}",
        "",
        "export interface Resistance {",
        "  channel: string;",
        "  modifier_pct: number;",
        "}",
        "",
        "export interface ActiveEffect {",
        "  ability_id: string;",
        "  name_it: string;",
        "  cost_ap: number;",
        "  effect_type: string;",
        "  target: string;",
        "  [key: string]: unknown;",
        "}",
        "",
        "export interface TraitMechanics {",
        "  attack_mod: number;",
        "  defense_mod: number;",
        "  damage_step: number;",
        "  cost_ap: number;",
        "  resistances: Resistance[];",
        "  active_effects: ActiveEffect[];",
        "}",
        "",
        "export type TraitId =",
    ]
    for tid in trait_ids:
        lines.append(f'  | "{tid}"')
    lines.append("  ;")
    lines.append("")
    lines.append("export type TraitCatalog = Record<TraitId, TraitMechanics>;")
    lines.append("")
    return "\n".join(lines)


def gen_json_schema(traits: dict, version: str) -> str:
    """Genera JSON Schema per trait_mechanics."""
    trait_ids = sorted(traits.keys())
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"traitMechanics.generated.v{version}",
        "title": f"Trait Mechanics Schema (auto-generated v{version})",
        "type": "object",
        "properties": {
            "schema_version": {"type": "string"},
            "traits": {
                "type": "object",
                "properties": {
                    tid: {
                        "type": "object",
                        "properties": {
                            "attack_mod": {"type": "integer"},
                            "defense_mod": {"type": "integer"},
                            "damage_step": {"type": "integer"},
                            "cost_ap": {"type": "integer", "minimum": 1, "maximum": 3},
                            "resistances": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "channel": {"type": "string"},
                                        "modifier_pct": {"type": "integer"},
                                    },
                                },
                            },
                        },
                    }
                    for tid in trait_ids
                },
                "additionalProperties": True,
            },
        },
    }
    return json.dumps(schema, indent=2, ensure_ascii=False)


def main():
    parser = argparse.ArgumentParser(description="Generate multi-target types from trait YAML")
    parser.add_argument("--input", default=DEFAULT_INPUT)
    parser.add_argument("--ts-out", default=TS_OUTPUT)
    parser.add_argument("--schema-out", default=SCHEMA_OUTPUT)
    args = parser.parse_args()

    data = load_yaml(args.input)
    traits = data.get("traits", {})
    version = data.get("schema_version", "?")

    # TypeScript
    ts_path = Path(args.ts_out)
    ts_path.parent.mkdir(parents=True, exist_ok=True)
    ts_path.write_text(gen_typescript(traits, version), encoding="utf-8")

    # JSON Schema
    schema_path = Path(args.schema_out)
    schema_path.parent.mkdir(parents=True, exist_ok=True)
    schema_path.write_text(gen_json_schema(traits, version), encoding="utf-8")

    print(f"[gen_trait_types] {len(traits)} traits -> TS:{ts_path} Schema:{schema_path}")


if __name__ == "__main__":
    main()
