name: telemetry
owner: Telemetry & Analytics
description: >-
  Profilo per le pipeline di raccolta telemetria e la validazione delle metriche VC.
env:
  GAME_CLI_DEFAULT_SEED: telemetry-smoke
  GAME_CLI_LOG_LEVEL: WARNING
  GAME_CLI_EXPECTED_CHANNEL: "#vc-telemetry"
smoke:
  commands:
    - validate-datasets
    - validate-ecosystem-pack --json-out logs/cli/telemetry-pack.json
    - roll-pack --seed telemetry-smoke ISFJ support
contacts:
  slack: "#vc-telemetry"
  leads:
    - nome: D. Errani
      ruolo: Telemetry Owner
