feature_flags:
  analytics:
    squadsync_view:
      description: "Abilita la pagina Analytics > SquadSync e il resolver GraphQL associato."
      default: false
      rollout:
        phase: canary
        cohorts:
          - analytics-team
          - qa-companion
      owner: analytics
      controls:
        contact: squad-sync@gamestudio.local
        playbook: docs/Canvas/feature-updates.md
      metrics:
        - "Engagement medio > 0.58 nelle squadre canary"
        - "Tempo medio stand-up < 11 minuti"
  idea_engine:
    feedback_enhancements:
      description: "Attiva il modulo feedback con fallback Slack #feedback-enhancements."
      default: true
      rollout:
        phase: general_availability
      owner: support_ops
      controls:
        contact: support-qa@gamestudio.local
        slack: "#feedback-enhancements"
        playbook: docs/tutorials/idea-engine-feedback.md
      metrics:
        - "Tempo medio risposta feedback < 24h"
        - "Numero escalation Slack gestite per sprint >= 3"
