#!/usr/bin/env python3
"""Generate trait_native pseudo-job text-append in data/core/jobs.yaml.

Extracts every `active_effects[*]` entry under each trait in
packs/evo_tactics_pack/data/balance/trait_mechanics.yaml and emits a
`trait_native` pseudo-job text block, appending it to data/core/jobs.yaml
(or replacing existing trait_native block if present).

Text-based emission preserves all existing job entries verbatim (no
yaml.safe_dump round-trip → no style noise on diff). Idempotent.

abilityExecutor.js scans `catalog.jobs.*.abilities` so this exposes all
39 trait-native ability_ids without code change. Each ability gets
`source: trait` marker for downstream filtering.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
TRAIT_MECH = REPO / "packs/evo_tactics_pack/data/balance/trait_mechanics.yaml"
JOBS = REPO / "data/core/jobs.yaml"

TRAIT_NATIVE_BLOCK_MARKER_END = (
    "  # END trait_native (auto-generated by scripts/generate_trait_native_abilities.py)"
)


def load_trait_active_effects(path: Path) -> list[tuple[str, dict]]:
    """Return list of (trait_id, ability dict) tuples flattened."""
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    traits = data.get("traits", {})
    out: list[tuple[str, dict]] = []
    for trait_id, body in traits.items():
        if not isinstance(body, dict):
            continue
        effects = body.get("active_effects") or []
        for eff in effects:
            if not isinstance(eff, dict) or not eff.get("ability_id"):
                continue
            out.append((trait_id, eff))
    return out


def _format_dice(d: dict) -> str:
    """Inline flow-style dice block matching existing jobs.yaml convention."""
    return (
        f"{{ count: {d.get('count', 1)}, sides: {d.get('sides', 6)}, "
        f"modifier: {d.get('modifier', 0)} }}"
    )


def _default_target(effect_type: str) -> str:
    if effect_type in ("buff", "heal"):
        return "self"
    if effect_type in ("damage", "apply_status"):
        return "enemy"
    return "self"


def emit_ability_yaml(ability_id: str, trait_id: str, eff: dict) -> str:
    """Produce a YAML ability block under trait_native abilities, indent-6."""
    out: list[str] = []
    out.append(f"      trait_{ability_id}:")
    out.append(f"        ability_id: {ability_id}")
    name = eff.get("name_it", ability_id)
    out.append(f'        name_it: "{name}"')
    description = f"Abilità nativa del trait {trait_id}."
    out.append(f'        description_it: "{description}"')
    out.append(f"        cost_ap: {eff.get('cost_ap', 2)}")
    out.append("        cost_pi: 0")
    effect_type = eff.get("effect_type", "buff")
    out.append(f"        effect_type: {effect_type}")
    if "buff_stat" in eff:
        out.append(f"        buff_stat: {eff['buff_stat']}")
    if "buff_amount" in eff:
        out.append(f"        buff_amount: {eff['buff_amount']}")
    if "buff_duration" in eff:
        out.append(f"        buff_duration: {eff['buff_duration']}")
    if "heal_dice" in eff:
        out.append(f"        heal_dice: {_format_dice(eff['heal_dice'])}")
    if "damage_dice" in eff:
        out.append(f"        damage_dice: {_format_dice(eff['damage_dice'])}")
    if "channel" in eff:
        out.append(f"        channel: {eff['channel']}")
    if "status_id" in eff:
        out.append(f"        status_id: {eff['status_id']}")
    if "status_duration" in eff:
        out.append(f"        status_duration: {eff['status_duration']}")
    target = eff.get("target") or _default_target(effect_type)
    out.append(f"        target: {target}")
    out.append("        rank: 1")
    out.append("        source: trait")
    out.append(f"        trait_id: {trait_id}")
    return "\n".join(out)


def build_trait_native_block(entries: list[tuple[str, dict]]) -> str:
    """Build trait_native pseudo-job text block."""
    seen: set[str] = set()
    abilities_yaml: list[str] = []
    for trait_id, eff in entries:
        ability_id = eff["ability_id"]
        if ability_id in seen:
            print(
                f"WARN: duplicate ability_id '{ability_id}' skipped (first wins)",
                file=sys.stderr,
            )
            continue
        seen.add(ability_id)
        abilities_yaml.append(emit_ability_yaml(ability_id, trait_id, eff))

    block = (
        "\n"
        "  # Pseudo-job auto-generated by scripts/generate_trait_native_abilities.py.\n"
        "  # Indicizza abilità derivate da trait_mechanics.yaml active_effects per\n"
        "  # esposizione a abilityExecutor.js (catalog.jobs.*.abilities scan).\n"
        "  # Filtrato da GET /api/jobs via status: pseudo (apps/backend/routes/jobs.js).\n"
        "  # Non assegnabile come job principale a unit — abilità invocabili da\n"
        "  # qualunque unit possieda il trait_id sorgente referenziato.\n"
        "  trait_native:\n"
        "    id: trait_native\n"
        '    label: "Native (Trait)"\n'
        '    label_it: "Nativa (Trait)"\n'
        '    label_en: "Native (Trait)"\n'
        "    role: support\n"
        "    status: pseudo\n"
        '    description: "Pseudo-job indice trait-native abilities."\n'
        '    description_it: "Pseudo-job indice. Ogni unità eredita le abilità trait-native dei propri trait_id."\n'
        '    fantasy_flavor: "Le forme stesse parlano: ogni mutazione è un\'arma."\n'
        "    synergy_tags: []\n"
        "    initiative: 0\n"
        "    attack_range: 0\n"
        "    resource_usage: { primary: AP, secondary: AP }\n"
        "    abilities:\n"
        + "\n".join(abilities_yaml)
        + "\n"
        + TRAIT_NATIVE_BLOCK_MARKER_END
        + "\n"
    )
    return block


def upsert_block(jobs_path: Path, block: str) -> None:
    """Append trait_native block, or replace if existing block detected."""
    raw = jobs_path.read_text(encoding="utf-8")
    pattern = re.compile(
        r"\n\s*# Pseudo-job auto-generated by scripts/generate_trait_native_abilities\.py.*?"
        + re.escape(TRAIT_NATIVE_BLOCK_MARKER_END)
        + r"\n",
        re.DOTALL,
    )
    if pattern.search(raw):
        new = pattern.sub(block, raw)
    else:
        if not raw.endswith("\n"):
            raw += "\n"
        new = raw + block
    jobs_path.write_text(new, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="Write changes to jobs.yaml")
    ap.add_argument("--dry-run", action="store_true", help="Print block to stdout")
    args = ap.parse_args()

    entries = load_trait_active_effects(TRAIT_MECH)
    block = build_trait_native_block(entries)
    abilities_count = block.count("        ability_id:")
    print(
        f"Found {len(entries)} active_effects entries -> {abilities_count} unique abilities",
        file=sys.stderr,
    )

    if args.dry_run:
        sys.stdout.write(block)
        return 0
    if args.write:
        upsert_block(JOBS, block)
        print(
            f"OK: upserted trait_native ({abilities_count} abilities) into {JOBS}",
            file=sys.stderr,
        )
        return 0
    ap.print_help()
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
