schema_version: '1.0'
profiles:
  temperato_umido:
    T_mean:
    - 5
    - 18
    P_total:
    - 600
    - 1400
    salinita:
    - dolce
    hazard_bias:
    - vento_forte
    - pendenze_instabili
  arido_freddo:
    T_mean:
    - -10
    - 12
    P_total:
    - 100
    - 400
    salinita:
    - dolce
    - salina interna
    hazard_bias:
    - whiteout
    - ghiaccio_sottile
  arido_caldo:
    T_mean:
    - 10
    - 30
    P_total:
    - 0
    - 200
    salinita:
    - salina interna
    hazard_bias:
    - tempeste_sabbia
    - irraggiamento_alto
