schema_version: '1.0'
hazards:
- id: vento_forte
  requires_any_of:
  - build_cover
  - guard_stance
- id: pioggia_torpida
  requires_any_of:
  - ignore_fog_penalty
  - reveal_hidden_radius
- id: pendenze_instabili
  requires_any_of:
  - jump_bonus
  - pathing_bonus
- id: whiteout
  requires_any_of:
  - ignore_fog_penalty
  - reveal_hidden_radius
- id: ghiaccio_sottile
  requires_any_of:
  - landing_on_ice
  - jump_bonus
- id: tempeste_sabbia
  requires_any_of:
  - eye_protection
  - ignore_fog_penalty
- id: iron_shards
  requires_any_of:
  - dr_impact_cap
  - build_cover
  effect: 'schegge ferrose: danno su corsa senza protezione'
- id: magnetic_patches
  requires_any_of:
  - non_metal_gear
  - seal_vents
  effect: 'campi magnetici irregolari: penalità a gear metallico'
- id: shock_termici
  requires_any_of:
  - thermal_buffering
  - res_heat
  - res_cold
  effect: sbalzi estremi caldo/freddo che stressano strutture e fluidi
- id: geiser_criogenici
  requires_any_of:
  - pressure_tolerance
  - cryogenic_shell
  - geothermal_anchor
  effect: getti criogenici pressurizzati che congelano e scagliano in aria
- id: piogge_acide
  requires_any_of:
  - res_acid
  - detox_cycle
  - corrosion_shell
  effect: precipitazioni caustiche che dissolvono carapaci e filtri
- id: aerosol_solfurei
  requires_any_of:
  - respiratory_filters
  - detox_cycle
  - sealed_respirators
  effect: nebbie sulfuree irritanti e corrosive per apparati respiratori
- id: tempeste_salate
  requires_any_of:
  - res_salt
  - sealed_membranes
  - moisture_harvest
  effect: sabbie saline abrasive che estraggono acqua dai tessuti
- id: miraggi_termici
  requires_any_of:
  - thermal_navigation
  - heat_sense
  - polarized_vision
  effect: gradienti termici distorcenti che confondono percezione e traiettorie
- id: fulmini_perpetui
  requires_any_of:
  - res_electric
  - faraday_carapace
  - lightning_sense
  effect: scariche costanti e correnti ascendenti che fulminano lenti conduttivi
- id: shearing_winds
  requires_any_of:
  - stability_thrusters
  - wind_sense
  - anchor_claws
  effect: venti a forbice che destabilizzano volo e arrampicata
- id: sfiati_sulfurei
  requires_any_of:
  - res_acid
  - pressure_tolerance
  - detox_cycle
  effect: sfiati supercaldi saturi di zolfo e metalli pesanti
- id: frane_abissali
  requires_any_of:
  - anchor_clamps
  - seismic_sense
  - pressure_tolerance
  effect: crolli sottomarini improvvisi con onde d'urto e detrito
