schema_version: '1.0'
roles_enum:
- produttore
- produttore_chemiotrofo
- erbivoro_primario
- grazing
- filtratore_grazing
- predatore_secondario
- predatore_filtratore_secondario
- predatore_regolatore_simbionte
- predatore_terziario_apex
- decompositore
- impollinatore
- impollinatore_notturno
- commensale
- commensale_opportunista
- parassita
- parassita_acquatico
- detritivoro
- ingegneri_ecosistema
- onnivoro_invasivo
- minaccia_microbica
- evento_ecologico
- dispersore_ponte
compat_groups:
  produttore:
  - produttori
  decompositore:
  - decompositori
  impollinatore:
  - impollinatori
  predatore_terziario_apex:
  - consumatori_terziari
  - specie_chiave
