schema_version: 1.5
biome: cryosteppe
requirements:
  groups: [predatori, prede, erbivori, impollinatori, dispersori_semi, simbionti, commensali, parassiti, detritivori, decompositori, filtratori, ingegneri_ecosistema, specie_chiave, ombrello_indicatori, invasive]
  at_least: {sentient: 1, apex: 1, keystone: 1, bridge: 1, threat: 1, event: 1}
species_dirs: [packs/evo_tactics_pack/data/species/cryosteppe]
