#!/usr/bin/env python3
"""Bulk promotion of doc_status based on path prefix rules.

One-time cleanup after the bulk migration of PR #1309, which assigned
'doc_status: draft' to ~460 docs by default. This script reclassifies docs
to their appropriate status based on stable path-based categories:

- 'active':         canonical reference docs that don't need ongoing work
- 'historical_ref': archived/legacy content kept for reference
- 'generated':      auto-regenerated by CI/scripts
- 'draft' (no-op):  genuine work-in-progress

The script updates BOTH the registry entry and the file's frontmatter
in-sync to avoid 'frontmatter_registry_mismatch' warnings.

Usage:
    python tools/docs_status_promotion.py            # apply changes
    python tools/docs_status_promotion.py --dry-run  # preview only
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Iterable, Optional, Tuple

REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = REPO_ROOT / "docs" / "governance" / "docs_registry.json"


# Path prefix -> target doc_status
# Rules are applied in order; first match wins. Prefixes are 'startswith' matches.
PROMOTION_RULES: list[Tuple[str, str]] = [
    # --- ACTIVE: canonical reference docs ---
    ("docs/core/", "active"),
    ("docs/hubs/", "active"),
    ("docs/adr/", "active"),
    ("docs/guide/", "active"),
    ("docs/governance/", "active"),
    ("docs/tutorials/", "active"),
    ("docs/architecture/", "active"),
    ("docs/appendici/", "active"),
    ("docs/catalog/", "active"),
    ("docs/biomes/", "active"),
    # --- HISTORICAL_REF: archived/legacy content ---
    ("docs/archive/", "historical_ref"),
    ("docs/playtest/", "historical_ref"),
    ("docs/presentations/", "historical_ref"),
    ("docs/evo-tactics/", "historical_ref"),
    # --- GENERATED: auto-regenerated files ---
    ("docs/reports/", "generated"),
    ("docs/logs/", "generated"),
    ("docs/generated/", "generated"),
    ("reports/", "generated"),
]


# Explicit root-level files to promote to 'active'.
# (These don't match a directory prefix so they need an exact list.)
ROOT_FILES_TO_PROMOTE: set[str] = {
    "AGENTS.md",
    "AGENT_WORKFLOW_GUIDE.md",
    "CLAUDE.md",
    "CONTRIBUTING.md",
    "MASTER_PROMPT.md",
    "PULL_REQUEST_TEMPLATE.md",
    "README.md",
    "router.md",
    "agent.md",
    "agent_constitution.md",
}


def determine_target_status(path: str) -> Optional[str]:
    """Return the target doc_status for a given path, or None if no rule applies."""
    normalized = path.replace("\\", "/")
    if normalized in ROOT_FILES_TO_PROMOTE:
        return "active"
    for prefix, target in PROMOTION_RULES:
        if normalized.startswith(prefix):
            return target
    return None


def update_frontmatter_status(path: Path, new_status: str) -> bool:
    """Update the doc_status field in a file's YAML frontmatter in-place.

    Returns True if the file was modified, False otherwise.
    """
    if not path.exists():
        return False
    try:
        text = path.read_text(encoding="utf-8-sig")
    except (OSError, UnicodeDecodeError):
        return False

    lines = text.splitlines(keepends=True)
    if not lines or lines[0].rstrip() != "---":
        # No frontmatter — nothing to update
        return False

    # Find closing ---
    end_idx = None
    for idx in range(1, len(lines)):
        if lines[idx].rstrip() == "---":
            end_idx = idx
            break
    if end_idx is None:
        return False

    updated = False
    for idx in range(1, end_idx):
        line = lines[idx]
        stripped = line.lstrip()
        if stripped.startswith("doc_status:"):
            # Preserve original indentation + newline
            indent = line[: len(line) - len(stripped)]
            newline = "\n" if line.endswith("\n") else ""
            lines[idx] = f"{indent}doc_status: {new_status}{newline}"
            updated = True
            break

    if updated:
        path.write_text("".join(lines), encoding="utf-8")
    return updated


def promote(dry_run: bool = False) -> dict:
    """Run the promotion pass. Returns a summary dict."""
    registry = json.loads(REGISTRY_PATH.read_text(encoding="utf-8-sig"))

    promoted: dict[str, int] = {"active": 0, "historical_ref": 0, "generated": 0}
    unchanged = 0
    skipped_no_file = 0
    already_correct = 0

    for entry in registry["entries"]:
        path = entry.get("path", "")
        current_status = entry.get("doc_status", "draft")
        target_status = determine_target_status(path)

        if target_status is None:
            unchanged += 1
            continue

        if current_status == target_status:
            already_correct += 1
            continue

        # Also skip already-non-draft statuses that are MORE specific than the
        # path rule would assign (e.g., a superseded doc in docs/guide/ shouldn't
        # get bumped back to active).
        if current_status in ("superseded", "legacy_active"):
            unchanged += 1
            continue

        # Update registry entry
        if not dry_run:
            entry["doc_status"] = target_status

        # Update frontmatter on disk
        abs_path = REPO_ROOT / path
        if not abs_path.exists():
            skipped_no_file += 1
            continue

        if not dry_run:
            update_frontmatter_status(abs_path, target_status)

        promoted[target_status] = promoted.get(target_status, 0) + 1

    if not dry_run:
        registry["entries"] = sorted(
            registry["entries"], key=lambda e: e.get("path", "")
        )
        REGISTRY_PATH.write_text(
            json.dumps(registry, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )

    return {
        "promoted": promoted,
        "total_promoted": sum(promoted.values()),
        "unchanged": unchanged,
        "already_correct": already_correct,
        "skipped_no_file": skipped_no_file,
        "dry_run": dry_run,
    }


def print_summary(summary: dict) -> None:
    print("=" * 60)
    print(f"DOC STATUS PROMOTION REPORT ({'DRY RUN' if summary['dry_run'] else 'APPLIED'})")
    print("=" * 60)
    print(f"  active:         {summary['promoted']['active']}")
    print(f"  historical_ref: {summary['promoted']['historical_ref']}")
    print(f"  generated:      {summary['promoted']['generated']}")
    print(f"  -----")
    print(f"  total promoted: {summary['total_promoted']}")
    print()
    print(f"  already correct:     {summary['already_correct']}")
    print(f"  unchanged (no rule): {summary['unchanged']}")
    print(f"  skipped (no file):   {summary['skipped_no_file']}")
    print("=" * 60)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview changes without writing anything.",
    )
    args = parser.parse_args()

    if not REGISTRY_PATH.exists():
        print(f"ERROR: registry not found at {REGISTRY_PATH}", file=sys.stderr)
        return 2

    summary = promote(dry_run=args.dry_run)
    print_summary(summary)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
