title: Evo-Tactics Species Schema v1.5 (DriftLocked++)
type: object
required: [schema_version, receipt, id, display_name, biomes, role_trofico, functional_tags, vc, playable_unit, spawn_rules, balance]
properties:
  schema_version: {const: 1.5}
  receipt: {type: object, required: [source, author, date, trace_hash]}
  id: {type: string, pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$'}
  biomes: {type: array, minItems: 1, uniqueItems: true}
  role_trofico: {type: string}
  vc: {type: object}
  spawn_rules: {type: object, required: [densita]}
  balance: {type: object, required: [encounter_role]}
