name: CI Evo Tactics

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps
        run: pip install pyyaml jsonschema pytest
      - name: Validate YAML and JSON
        run: |
          python - <<'PY'
import os, json, sys
from pathlib import Path
import yaml
root = Path('.')
ok = True
for p in root.rglob('*.json'):
    try:
        json.loads(p.read_text(encoding='utf-8'))
    except Exception as e:
        print('JSON ERROR:', p, e); ok=False
for p in root.rglob('*.yml'):
    try:
        yaml.safe_load(p.read_text(encoding='utf-8'))
    except Exception as e:
        print('YAML ERROR:', p, e); ok=False
for p in root.rglob('*.yaml'):
    try:
        yaml.safe_load(p.read_text(encoding='utf-8'))
    except Exception as e:
        print('YAML ERROR:', p, e); ok=False
sys.exit(0 if ok else 1)
PY
      - name: Run schema tests
        run: pytest -q
