name: ci-minimal

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: tools/ts/package-lock.json

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: tools/ts

      - name: Run npm test
        run: npm test
        working-directory: tools/ts

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: tools/py/requirements.txt

      - name: Install Python dependencies
        run: pip install -r tools/py/requirements.txt

      - name: Run pytest
        run: pytest
