name: Daily PR Summary

on:
  schedule:
    - cron: '10 17 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r tools/py/requirements.txt

      - name: Generate daily PR summary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python tools/py/daily_pr_report.py \
            --repo "${{ github.repository }}" \
            --date "$(date -u +%Y-%m-%d)"

      - name: Commit changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/changelog.md docs/piani/roadmap.md docs/checklist/action-items.md docs/Canvas/feature-updates.md docs/chatgpt_changes/
          git commit -m "chore: aggiorna riepilogo PR giornaliero"
          git push
